apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: orchestrator
type: Opaque
stringData:
  INVENTORY_DB_USER: "user01"
  INVENTORY_DB_PASSWORD: "postgres"
  INVENTORY_DB_NAME: "inventory_db"
  BILLING_DB_USER: "user01"
  BILLING_DB_PASSWORD: "password"
  BILLING_DB_NAME: "billing_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: orchestrator
type: Opaque
stringData:
  RABBITMQ_USER: "rabbit"
  RABBITMQ_PASSWORD: "password"
  RABBITMQ_QUEUE: "billing_queue"
