apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  namespace: orchestrator
spec:
  selector:
    app: inventory-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
  namespace: orchestrator
spec:
  serviceName: inventory-db
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
      - name: postgres
        image: k3d-registry.localhost:5000/inventory-db:latest
        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: INVENTORY_DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: INVENTORY_DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: INVENTORY_DB_NAME
        volumeMounts:
        - name: inventory-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: inventory-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
