apiVersion: v1
kind: Service
metadata:
  name: inventory-app
  namespace: orchestrator
spec:
  selector:
    app: inventory-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  namespace: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory-app
        image: k3d-registry.localhost:5000/inventory-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: INVENTORY_APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: INVENTORY_APP_PORT
        - name: INVENTORY_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: INVENTORY_DB_USER
        - name: INVENTORY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: INVENTORY_DB_PASSWORD
        - name: INVENTORY_DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: INVENTORY_DB_NAME
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-app-hpa
  namespace: orchestrator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
